// scripts/seed-cards.ts
// One-time script to seed your database with known Canadian credit cards
// Run: npx ts-node scripts/seed-cards.ts

import { supabaseAdmin } from '../lib/supabase'

const SEED_CARDS = [
  // ── American Express ──
  {
    issuer_slug: 'amex',
    name: 'American Express Cobalt Card',
    slug: 'amex-cobalt',
    card_type: 'amex',
    card_network: 'American Express',
    tier: 'entry',
    annual_fee: 155.88,
    annual_fee_waived_first_year: false,
    rewards_program: 'Amex MR',
    rewards_type: 'points',
    earn_rate_base: 1,
    earn_rate_multipliers: { dining: 5, groceries: 5, streaming: 3, travel: 2 },
    transfer_partners: ['Aeroplan', 'British Airways', 'Air France', 'Hilton', 'Marriott'],
    lounge_access: false,
    travel_insurance: true,
    purchase_protection: true,
    foreign_transaction_fee: 2.5,
    credit_score_min: 'good',
    apply_url: 'https://www.americanexpress.com/en-ca/credit-cards/cobalt-card/',
    tags: ['amex', 'cobalt', 'dining', 'points', 'no-lounge'],
    is_featured: true,
    short_description: 'Best everyday card for dining and grocery rewards',
    pros: ['5x points on dining and groceries', '3x on streaming services', '2x on travel', 'Transfer to Aeroplan and airlines'],
    cons: ['$12.99/month fee — never waived', 'No lounge access', '2.5% foreign transaction fee'],
    best_for: ['foodies', 'everyday spenders', 'points collectors'],
    min_income: 0,
    card_color: '#2C5F8A',
  },
  {
    issuer_slug: 'amex',
    name: 'The Platinum Card® from American Express',
    slug: 'amex-platinum',
    card_type: 'amex',
    card_network: 'American Express',
    tier: 'super-premium',
    annual_fee: 799,
    annual_fee_waived_first_year: false,
    rewards_program: 'Amex MR',
    rewards_type: 'points',
    earn_rate_base: 1,
    earn_rate_multipliers: { travel: 3, dining: 2 },
    transfer_partners: ['Aeroplan', 'British Airways', 'Air France', 'Emirates', 'Hilton', 'Marriott'],
    lounge_access: true,
    travel_insurance: true,
    purchase_protection: true,
    foreign_transaction_fee: 0,
    credit_score_min: 'excellent',
    apply_url: 'https://www.americanexpress.com/en-ca/charge-cards/the-platinum-card/',
    tags: ['amex', 'platinum', 'lounge', 'no-fx-fee', 'premium', 'travel'],
    is_featured: true,
    short_description: 'Ultra-premium travel card with unlimited lounge access',
    pros: ['Unlimited Priority Pass lounge access', 'No foreign transaction fees', '$200 annual travel credit', 'Hotel elite status with Marriott and Hilton'],
    cons: ['$799 annual fee', 'Charge card — balance due monthly', 'High spend threshold for welcome bonus'],
    best_for: ['frequent travelers', 'lounge lovers', 'premium spenders'],
    min_income: 0,
    card_color: '#A8A9AD',
  },
  {
    issuer_slug: 'amex',
    name: 'American Express® Gold Rewards Card',
    slug: 'amex-gold-rewards',
    card_type: 'amex',
    card_network: 'American Express',
    tier: 'mid',
    annual_fee: 250,
    annual_fee_waived_first_year: false,
    rewards_program: 'Amex MR',
    rewards_type: 'points',
    earn_rate_base: 1,
    earn_rate_multipliers: { travel: 2, gas: 2, groceries: 2 },
    transfer_partners: ['Aeroplan', 'British Airways', 'Air France'],
    lounge_access: false,
    travel_insurance: true,
    purchase_protection: true,
    foreign_transaction_fee: 2.5,
    credit_score_min: 'good',
    apply_url: 'https://www.americanexpress.com/en-ca/credit-cards/gold-rewards-card/',
    tags: ['amex', 'gold', 'travel', 'points'],
    short_description: 'Flexible Amex MR points on travel, gas, and groceries',
    pros: ['2x points on travel, gas, and grocery', 'Transfer to Aeroplan and partner airlines', 'Comprehensive travel insurance'],
    cons: ['$250 annual fee', '2.5% foreign transaction fee', 'No lounge access'],
    best_for: ['travelers', 'everyday spenders', 'flexible rewards seekers'],
    min_income: 0,
    card_color: '#C9A227',
  },
  {
    issuer_slug: 'amex',
    name: 'SimplyCash™ Preferred Card from American Express',
    slug: 'amex-simplycash-preferred',
    card_type: 'amex',
    card_network: 'American Express',
    tier: 'mid',
    annual_fee: 99,
    annual_fee_waived_first_year: false,
    rewards_program: null,
    rewards_type: 'cashback',
    earn_rate_base: 2,
    earn_rate_multipliers: { gas: 4, groceries: 4 },
    lounge_access: false,
    travel_insurance: true,
    purchase_protection: true,
    foreign_transaction_fee: 2.5,
    credit_score_min: 'good',
    apply_url: 'https://www.americanexpress.com/en-ca/credit-cards/simply-cash-preferred/',
    tags: ['amex', 'cashback', 'groceries', 'gas'],
    short_description: 'Top Amex cash back card with elevated grocery and gas rates',
    pros: ['4% cash back on gas and groceries', '2% cash back on everything else', 'Travel and purchase insurance'],
    cons: ['$99 annual fee', '2.5% foreign transaction fee', 'Cash back paid as statement credit annually'],
    best_for: ['cash back seekers', 'grocery shoppers', 'drivers'],
    min_income: 0,
    card_color: '#1B4D8E',
  },

  // ── TD ──
  {
    issuer_slug: 'td',
    name: 'TD Aeroplan Visa Infinite Card',
    slug: 'td-aeroplan-visa-infinite',
    card_type: 'visa',
    card_network: 'Visa',
    tier: 'premium',
    annual_fee: 139,
    annual_fee_waived_first_year: false,
    rewards_program: 'Aeroplan',
    rewards_type: 'points',
    earn_rate_base: 1,
    earn_rate_multipliers: { groceries: 1.5, gas: 1.5, travel: 1.5, dining: 1.5 },
    transfer_partners: ['Air Canada', 'Air France', 'United', 'Lufthansa'],
    lounge_access: false,
    travel_insurance: true,
    purchase_protection: true,
    foreign_transaction_fee: 2.5,
    credit_score_min: 'good',
    apply_url: 'https://www.td.com/ca/en/personal-banking/products/credit-cards/travel/aeroplan-visa-infinite-card/',
    tags: ['td', 'aeroplan', 'travel', 'visa-infinite'],
    is_featured: true,
    short_description: 'Top Aeroplan card for Air Canada loyalists',
    pros: ['1.5x Aeroplan on groceries, gas, travel and dining', 'Free first checked bag on Air Canada', 'Comprehensive travel insurance package'],
    cons: ['$139 annual fee', '2.5% foreign transaction fee', 'No lounge access'],
    best_for: ['Air Canada flyers', 'Aeroplan collectors', 'travelers'],
    min_income: 60000,
    card_color: '#2B6CB0',
  },
  {
    issuer_slug: 'td',
    name: 'TD First Class Travel Visa Infinite Card',
    slug: 'td-first-class-travel',
    card_type: 'visa',
    card_network: 'Visa',
    tier: 'premium',
    annual_fee: 120,
    annual_fee_waived_first_year: false,
    rewards_program: 'TD Rewards',
    rewards_type: 'points',
    earn_rate_base: 2,
    earn_rate_multipliers: { travel: 9, dining: 6, groceries: 6 },
    lounge_access: false,
    travel_insurance: true,
    purchase_protection: true,
    foreign_transaction_fee: 2.5,
    credit_score_min: 'good',
    apply_url: 'https://www.td.com/ca/en/personal-banking/products/credit-cards/travel/first-class-travel-visa-infinite-card/',
    tags: ['td', 'td-rewards', 'travel', 'visa-infinite'],
    short_description: 'High earn rate on travel booked via Expedia for TD',
    pros: ['9x points on Expedia for TD travel bookings', '6x points on dining and groceries', 'Travel and medical insurance included'],
    cons: ['$120 annual fee', 'TD Rewards less flexible than Aeroplan', '2.5% foreign transaction fee'],
    best_for: ['frequent travelers', 'diners', 'TD customers'],
    min_income: 60000,
    card_color: '#1A5276',
  },

  // ── Scotiabank ──
  {
    issuer_slug: 'scotiabank',
    name: 'Scotiabank Passport™ Visa Infinite* Card',
    slug: 'scotiabank-passport-visa-infinite',
    card_type: 'visa',
    card_network: 'Visa',
    tier: 'premium',
    annual_fee: 150,
    annual_fee_waived_first_year: false,
    rewards_program: 'Scene+',
    rewards_type: 'points',
    earn_rate_base: 1,
    earn_rate_multipliers: { groceries: 3, dining: 3, other: 3 },
    lounge_access: true,
    travel_insurance: true,
    purchase_protection: true,
    foreign_transaction_fee: 0,
    credit_score_min: 'very-good',
    apply_url: 'https://www.scotiabank.com/ca/en/personal/credit-cards/visa/passport-visa-infinite-card.html',
    tags: ['scotiabank', 'scene-plus', 'travel', 'no-fx-fee', 'lounge', 'visa-infinite'],
    is_featured: true,
    short_description: 'Best no-FX-fee card with complimentary lounge access',
    pros: ['No foreign transaction fees', '6 free airport lounge passes per year', '3x Scene+ on dining, grocery, and entertainment'],
    cons: ['$150 annual fee', 'Scene+ redemptions less flexible than transferable points'],
    best_for: ['international travelers', 'no-fx-fee seekers', 'lounge users'],
    min_income: 60000,
    card_color: '#E31837',
  },
  {
    issuer_slug: 'scotiabank',
    name: 'Scotia Momentum® Visa Infinite* Card',
    slug: 'scotiabank-momentum-visa-infinite',
    card_type: 'visa',
    card_network: 'Visa',
    tier: 'premium',
    annual_fee: 120,
    annual_fee_waived_first_year: false,
    rewards_program: null,
    rewards_type: 'cashback',
    earn_rate_base: 1,
    earn_rate_multipliers: { groceries: 4, other: 4, gas: 2, transit: 2 },
    lounge_access: false,
    travel_insurance: true,
    purchase_protection: true,
    foreign_transaction_fee: 2.5,
    credit_score_min: 'good',
    apply_url: 'https://www.scotiabank.com/ca/en/personal/credit-cards/visa/momentum-visa-infinite-card.html',
    tags: ['scotiabank', 'cashback', 'groceries'],
    short_description: 'Highest cash back on groceries and recurring bills in Canada',
    pros: ['4% cash back on groceries and recurring bills', '2% on gas and transit', 'Travel insurance included'],
    cons: ['$120 annual fee', '2.5% foreign transaction fee', 'Cash back paid once per year'],
    best_for: ['grocery shoppers', 'cash back seekers', 'families'],
    min_income: 60000,
    card_color: '#C41230',
  },

  // ── BMO ──
  {
    issuer_slug: 'bmo',
    name: 'BMO eclipse Visa Infinite* Card',
    slug: 'bmo-eclipse-visa-infinite',
    card_type: 'visa',
    card_network: 'Visa',
    tier: 'premium',
    annual_fee: 120,
    annual_fee_waived_first_year: true,
    rewards_program: 'BMO Rewards',
    rewards_type: 'points',
    earn_rate_base: 1,
    earn_rate_multipliers: { groceries: 5, dining: 5, gas: 5, transit: 5 },
    lounge_access: false,
    travel_insurance: true,
    purchase_protection: true,
    foreign_transaction_fee: 2.5,
    credit_score_min: 'good',
    apply_url: 'https://www.bmo.com/en-ca/main/personal/credit-cards/bmo-eclipse-visa-infinite-card/',
    tags: ['bmo', 'bmo-rewards', 'groceries', 'dining'],
    is_featured: true,
    short_description: 'Elevated BMO Rewards points on everyday spending categories',
    pros: ['5x points on dining, groceries, gas and transit', 'First year annual fee waived', '$50 annual lifestyle credit'],
    cons: ['$120 annual fee from year 2', '2.5% foreign transaction fee', 'BMO Rewards less flexible than transferable currencies'],
    best_for: ['everyday spenders', 'foodies', 'transit users'],
    min_income: 60000,
    card_color: '#003DA5',
  },

  // ── RBC ──
  {
    issuer_slug: 'rbc',
    name: 'RBC Avion Visa Infinite Card',
    slug: 'rbc-avion-visa-infinite',
    card_type: 'visa',
    card_network: 'Visa',
    tier: 'premium',
    annual_fee: 120,
    annual_fee_waived_first_year: false,
    rewards_program: 'Avion',
    rewards_type: 'points',
    earn_rate_base: 1,
    earn_rate_multipliers: { travel: 1.25 },
    transfer_partners: ['British Airways', 'WestJet', 'American Airlines'],
    lounge_access: false,
    travel_insurance: true,
    purchase_protection: true,
    foreign_transaction_fee: 2.5,
    credit_score_min: 'good',
    apply_url: 'https://www.rbcroyalbank.com/credit-cards/avion-visa-infinite.html',
    tags: ['rbc', 'avion', 'travel', 'british-airways'],
    short_description: 'Flexible Avion points with airline and merchandise redemptions',
    pros: ['Transfer to British Airways, WestJet and American Airlines', 'Comprehensive travel insurance', 'Visa Infinite concierge service'],
    cons: ['$120 annual fee', '2.5% foreign transaction fee', 'No lounge access'],
    best_for: ['travelers', 'flexible points seekers', 'RBC customers'],
    min_income: 60000,
    card_color: '#003168',
  },
  {
    issuer_slug: 'rbc',
    name: 'WestJet RBC World Elite Mastercard',
    slug: 'westjet-rbc-world-elite',
    card_type: 'mastercard',
    card_network: 'Mastercard',
    tier: 'premium',
    annual_fee: 119,
    annual_fee_waived_first_year: false,
    rewards_program: 'WestJet Dollars',
    rewards_type: 'points',
    earn_rate_base: 1.5,
    earn_rate_multipliers: { travel: 2 },
    lounge_access: false,
    travel_insurance: true,
    purchase_protection: true,
    foreign_transaction_fee: 0,
    credit_score_min: 'good',
    apply_url: 'https://www.rbcroyalbank.com/credit-cards/westjet-world-elite-mastercard.html',
    tags: ['rbc', 'westjet', 'no-fx-fee', 'cashback'],
    short_description: 'Best card for WestJet flyers with no foreign transaction fees',
    pros: ['No foreign transaction fees', 'Annual companion voucher (round trip)', '1.5% WestJet dollars on all purchases'],
    cons: ['$119 annual fee', 'WestJet dollars locked to WestJet ecosystem', 'No lounge access'],
    best_for: ['WestJet flyers', 'no-fx-fee seekers', 'domestic travelers'],
    min_income: 80000,
    card_color: '#024DA1',
  },

  // ── CIBC ──
  {
    issuer_slug: 'cibc',
    name: 'CIBC Aeroplan® Visa Infinite* Card',
    slug: 'cibc-aeroplan-visa-infinite',
    card_type: 'visa',
    card_network: 'Visa',
    tier: 'premium',
    annual_fee: 139,
    annual_fee_waived_first_year: false,
    rewards_program: 'Aeroplan',
    rewards_type: 'points',
    earn_rate_base: 1,
    earn_rate_multipliers: { groceries: 1.5, gas: 1.5, travel: 1.5, dining: 1.5 },
    transfer_partners: ['Air Canada', 'Air France', 'United'],
    lounge_access: false,
    travel_insurance: true,
    purchase_protection: true,
    foreign_transaction_fee: 2.5,
    credit_score_min: 'good',
    apply_url: 'https://www.cibc.com/en/personal-banking/credit-cards/travel/aeroplan-visa-infinite-card.html',
    tags: ['cibc', 'aeroplan', 'travel', 'visa-infinite'],
    short_description: 'Earn Aeroplan points with CIBC banking integration',
    pros: ['1.5x Aeroplan on groceries, gas, travel and dining', 'Free checked bag on Air Canada', 'Travel insurance package'],
    cons: ['$139 annual fee', '2.5% foreign transaction fee', 'No lounge access'],
    best_for: ['Air Canada flyers', 'CIBC customers', 'Aeroplan collectors'],
    min_income: 60000,
    card_color: '#C41F3A',
  },
  {
    issuer_slug: 'cibc',
    name: 'CIBC Dividend® Visa Infinite* Card',
    slug: 'cibc-dividend-visa-infinite',
    card_type: 'visa',
    card_network: 'Visa',
    tier: 'premium',
    annual_fee: 120,
    annual_fee_waived_first_year: true,
    rewards_program: null,
    rewards_type: 'cashback',
    earn_rate_base: 1,
    earn_rate_multipliers: { groceries: 4, gas: 4, transit: 2, other: 2 },
    lounge_access: false,
    travel_insurance: true,
    purchase_protection: true,
    foreign_transaction_fee: 2.5,
    credit_score_min: 'good',
    apply_url: 'https://www.cibc.com/en/personal-banking/credit-cards/cash-back/dividend-visa-infinite-card.html',
    tags: ['cibc', 'cashback', 'groceries', 'gas'],
    short_description: 'Strong cash back on groceries and gas — first year free',
    pros: ['4% cash back on groceries and gas', 'First year annual fee waived', '2% on transit and recurring bills'],
    cons: ['$120 annual fee from year 2', '2.5% foreign transaction fee', 'Cash back paid once per year'],
    best_for: ['cash back seekers', 'grocery shoppers', 'first card upgraders'],
    min_income: 60000,
    card_color: '#B22222',
  },

  // ── MBNA ──
  {
    issuer_slug: 'mbna',
    name: 'MBNA Rewards Mastercard',
    slug: 'mbna-rewards-mastercard',
    card_type: 'mastercard',
    card_network: 'Mastercard',
    tier: 'no-fee',
    annual_fee: 0,
    annual_fee_waived_first_year: false,
    rewards_program: 'MBNA Rewards',
    rewards_type: 'points',
    earn_rate_base: 1,
    earn_rate_multipliers: { dining: 5, groceries: 5, other: 5, streaming: 5 },
    lounge_access: false,
    travel_insurance: false,
    purchase_protection: true,
    foreign_transaction_fee: 2.5,
    credit_score_min: 'fair',
    apply_url: 'https://www.mbna.ca/en_CA/credit-cards/rewards/mbna-rewards-mastercard/',
    tags: ['mbna', 'no-fee', 'rewards', 'dining', 'groceries'],
    is_featured: false,
    short_description: 'No-fee card with 5x MBNA Rewards on everyday categories',
    pros: ['No annual fee', '5x points on dining, groceries, entertainment, digital, and memberships', 'Easy approval with fair credit'],
    cons: ['5x capped at first $5,000 spent/year per category', '2.5% foreign transaction fee', 'No travel insurance'],
    best_for: ['beginners', 'no-fee seekers', 'dining and grocery spenders'],
    min_income: 0,
    card_color: '#1A1A2E',
  },
  {
    issuer_slug: 'mbna',
    name: 'MBNA True Line Mastercard',
    slug: 'mbna-trueline-mastercard',
    card_type: 'mastercard',
    card_network: 'Mastercard',
    tier: 'no-fee',
    annual_fee: 0,
    annual_fee_waived_first_year: false,
    rewards_program: null,
    rewards_type: 'cashback',
    earn_rate_base: 0,
    lounge_access: false,
    travel_insurance: false,
    purchase_protection: false,
    foreign_transaction_fee: 2.5,
    credit_score_min: 'fair',
    apply_url: 'https://www.mbna.ca/en_CA/credit-cards/low-rate/mbna-true-line-mastercard/',
    tags: ['mbna', 'no-fee', 'low-interest', 'balance-transfer'],
    is_featured: false,
    short_description: 'Best low-interest card for carrying a balance at 8.99%',
    pros: ['No annual fee', '8.99% purchase interest rate', 'Ideal for balance transfers', 'No rewards complexity'],
    cons: ['No rewards or cash back', '2.5% foreign transaction fee', 'No travel or purchase insurance'],
    best_for: ['balance carriers', 'debt reducers', 'low-interest seekers'],
    min_income: 0,
    card_color: '#2C3E50',
  },
  {
    issuer_slug: 'mbna',
    name: 'MBNA Alaska Airlines Mastercard',
    slug: 'mbna-alaska-airlines-mastercard',
    card_type: 'mastercard',
    card_network: 'Mastercard',
    tier: 'entry',
    annual_fee: 75,
    annual_fee_waived_first_year: true,
    rewards_program: 'Alaska Mileage Plan',
    rewards_type: 'points',
    earn_rate_base: 1.5,
    earn_rate_multipliers: { travel: 3 },
    transfer_partners: ['Alaska Airlines', 'American Airlines', 'British Airways', 'Cathay Pacific', 'Japan Airlines'],
    lounge_access: false,
    travel_insurance: true,
    purchase_protection: true,
    foreign_transaction_fee: 2.5,
    credit_score_min: 'good',
    apply_url: 'https://www.mbna.ca/en_CA/credit-cards/travel/mbna-alaska-airlines-mastercard/',
    tags: ['mbna', 'alaska-airlines', 'travel', 'points', 'mileage-plan'],
    is_featured: false,
    short_description: 'Earn Alaska Mileage Plan miles redeemable on 30+ airline partners',
    pros: ['First year fee waived', '3x miles on Alaska Airlines purchases', 'Redeem on 30+ airline partners including British Airways and Cathay Pacific', 'Travel insurance included'],
    cons: ['$75 annual fee from year 2', '2.5% foreign transaction fee', 'Less useful for non-Alaska flyers'],
    best_for: ['Alaska Airlines flyers', 'US travel frequent flyers', 'partner airline redemptions'],
    min_income: 0,
    card_color: '#00629B',
  },

  // ── Rogers Bank ──
  {
    issuer_slug: 'rogers-bank',
    name: 'Rogers Red World Elite Mastercard',
    slug: 'rogers-red-world-elite',
    card_type: 'mastercard',
    card_network: 'Mastercard',
    tier: 'premium',
    annual_fee: 0,
    annual_fee_waived_first_year: false,
    rewards_program: 'Rogers Cash Back',
    rewards_type: 'cashback',
    earn_rate_base: 1.5,
    earn_rate_multipliers: { foreign_currency: 3, other: 5 },
    lounge_access: false,
    travel_insurance: true,
    purchase_protection: true,
    foreign_transaction_fee: 2.5,
    credit_score_min: 'very-good',
    apply_url: 'https://www.rogersbank.com/en/world_elite_mastercard',
    tags: ['rogers', 'no-fee', 'cashback', 'usd', 'world-elite'],
    is_featured: false,
    short_description: 'Best no-fee card for USD purchases — 3% cash back offsets FX fees',
    pros: ['No annual fee', '3% cash back on USD purchases (nets 0.5% after 2.5% FX fee)', '5% on Rogers/Fido/Shaw services', '1.5% on everything else', 'Travel insurance at no cost'],
    cons: ['$80,000 personal income requirement', '2.5% foreign transaction fee (offset by 3% cash back)', 'Cash back applied as statement credit only'],
    best_for: ['cross-border shoppers', 'Rogers/Fido/Shaw customers', 'USD spenders', 'no-fee premium seekers'],
    min_income: 80000,
    card_color: '#E3001B',
  },
  {
    issuer_slug: 'rogers-bank',
    name: 'Rogers Red Mastercard',
    slug: 'rogers-red-mastercard',
    card_type: 'mastercard',
    card_network: 'Mastercard',
    tier: 'no-fee',
    annual_fee: 0,
    annual_fee_waived_first_year: false,
    rewards_program: 'Rogers Cash Back',
    rewards_type: 'cashback',
    earn_rate_base: 1,
    earn_rate_multipliers: { other: 2 },
    lounge_access: false,
    travel_insurance: false,
    purchase_protection: false,
    foreign_transaction_fee: 2.5,
    credit_score_min: 'fair',
    apply_url: 'https://www.rogersbank.com/en/red_mastercard',
    tags: ['rogers', 'no-fee', 'cashback', 'beginner'],
    is_featured: false,
    short_description: 'Simple no-fee cash back card for Rogers and Fido customers',
    pros: ['No annual fee', '2% cash back on Rogers/Fido/Shaw bills', '1% cash back on everything else', 'No income requirement'],
    cons: ['2.5% foreign transaction fee', 'No travel insurance', 'Lower earn rate than World Elite version'],
    best_for: ['Rogers/Fido/Shaw customers', 'beginners', 'no-fee seekers'],
    min_income: 0,
    card_color: '#CC0000',
  },

  // ── No-fee ──
  {
    issuer_slug: 'tangerine',
    name: 'Tangerine Money-Back Credit Card',
    slug: 'tangerine-money-back',
    card_type: 'mastercard',
    card_network: 'Mastercard',
    tier: 'no-fee',
    annual_fee: 0,
    annual_fee_waived_first_year: false,
    rewards_program: null,
    rewards_type: 'cashback',
    earn_rate_base: 0.5,
    earn_rate_multipliers: { groceries: 2, gas: 2, dining: 2 },
    lounge_access: false,
    travel_insurance: false,
    purchase_protection: false,
    foreign_transaction_fee: 2.5,
    credit_score_min: 'fair',
    apply_url: 'https://www.tangerine.ca/en/products/spending/creditcard/money-back',
    tags: ['no-fee', 'cashback', 'tangerine', 'beginner'],
    is_featured: true,
    short_description: 'Best no-fee cash back card for beginners',
    pros: ['No annual fee ever', '2% cash back in 2 chosen categories', 'No minimum income requirement', 'Monthly cash back payout'],
    cons: ['2.5% foreign transaction fee', 'No travel insurance', '0.5% on all other purchases'],
    best_for: ['beginners', 'no-fee seekers', 'cash back starters', 'students'],
    min_income: 0,
    card_color: '#F47920',
  },
]

async function seedCards() {
  console.log('Starting card seed...')
  let seeded = 0
  let errors = 0

  for (const card of SEED_CARDS) {
    const { data: issuer, error: issuerError } = await supabaseAdmin
      .from('issuers')
      .select('id')
      .eq('slug', card.issuer_slug)
      .single()

    if (issuerError || !issuer) {
      console.error(`Issuer not found: ${card.issuer_slug}`)
      errors++
      continue
    }

    const { issuer_slug, ...cardData } = card

    const { error } = await supabaseAdmin
      .from('credit_cards')
      .upsert(
        { ...cardData, issuer_id: issuer.id, is_active: true },
        { onConflict: 'slug' }
      )

    if (error) {
      console.error(`Failed to seed ${card.name}:`, error.message)
      errors++
    } else {
      console.log(`✅ ${card.name}`)
      seeded++
    }
  }

  console.log(`\nDone! ${seeded} cards seeded, ${errors} errors.`)
}

seedCards().catch(console.error)
